#publish your docker image to github container registry
name: publish
on: 
  push
  
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build and push the image
        run: |
          docker login --username anubhavpradhan --password ${{ secrets.GHCR_PAT }} ghcr.io
          docker build . --tag ghcr.io/anubhavpradhan/hello-world-ghcr:latest
          docker push ghcr.io/anubhavpradhan/hello-world-ghcr:latest
